app.py
from flask import Flask, request, render_template, redirect, url_for
from routes.blog import blog_blueprint

app = Flask(__name__)

app.register_blueprint(blog_blueprint, url_prefix='/blog')

@app.route("/base")
def base():
    return render_template("base.html")

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/blog")
def blog():
    return render_template("blog.html")

@app.route("/create")
def create():
    return render_template("create.html")

@app.route("/posts")
def posts():
    return render_template("posts.html")

@app.route("/logout")
def logout():
    return render_template("logout.html")

@app.route("/login")
def login_page():
    return render_template("login.html")

database = {'Patryk': '123',
            'Balecki': 'xyz', 
            'Jony': 'abc', 
            'Tony': 'pqr',
}

@app.route('/form_login', methods=['POST', 'GET'])
def handle_login():
    name1 = request.form['username']
    pwd = request.form['password']
    if name1 not in database:
        return render_template('login.html', 
                               info='Invalid User!')
    else:
        if database[name1] != pwd:
            return render_template('login.html', 
                                   info='Invalid Password!')
        else:
            return render_template('logout.html',
                                   name=name1)
 




if __name__ == "__main__":
    app.run(debug=True,host='0.0.0.0')

routes/blog.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for
import csv 
import os

blog_blueprint = Blueprint('blog', __name__)

@blog_blueprint.route('/blog')
def index():
    posts = read_posts
    return render_template('blog.html')

def read_posts():
    posts = []
    if not os.path.exists('posts.csv'):
        with open('posts.csv', mode='w', newline='') as file:
            fieldnames = ['id', 'title', 'content', 'author']
            writer = csv.DictWriter(file, fieldnames=fieldnames)
            writer.writeheader()

    else:
        with open('posts.csv', mode='r') as file:
            csv_reader = csv.DictReader(file)
            for row in csv_reader:
                posts.append(row)
    print("Posts read from CSV:", posts)            
    return posts

def write_post(post):
        with open('posts.csv', mode='a', newline='') as file:
            fieldnames = ['id', 'title', 'content', 'author']
            writer = csv.DictWriter(file, fieldnames=fieldnames)
            writer.writerow(post)

@blog_blueprint.route('/post/<int:post_id>')
def post(post_id):
    posts = read_posts()
    post = next((p for p in posts if int(p['id']) == post_id), None)
    if post:
        return render_template('posts.html', post=post)
    else:
        return "Post not found", 404
    
@blog_blueprint.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        author = request.form['author']
            
            
        posts = read_posts()
        new_id = max([int(post['id']) for post in posts]) + 1 if posts else 1
            
            
        new_post = {
                'id': new_id,
                'title': title,
                'content': content,
                'author': author
        }
            
            
        write_post(new_post)
            
            
        return redirect(url_for('blog.index'))

        return render_template('create.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/forms.css">

    <title>Jake Robinson | {% block title %} {% endblock %}</title>
</head>
<body>

    <!--NAV BAR-->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{url_for ('index')}}">Jake Robinson</a>
            <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                &#9776;
            </button>
            <div class="collapse navbar-collapse d-flex justify-content-end" id="exCollapsingNavbar">
                <ul class="nav navbar-nav">
                    <li class="nav-item"><a href="#" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Media</a></li>
                    <li class="nav-item"><a href="{{ url_for('blog.index') }}" class="nav-link">Blog</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                    <li class="dropdown order-1">
                        <button style="background:linear-gradient(-60deg, rgb(253, 211, 41) 45%, rgb(255, 255, 2) 55%);"
                          type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary rounded-pill"> Hire Me <span class="caret"></span></button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block body%}


    {% endblock%}

    <!--FOOTER-->
  
    <footer class="bg-dark text-center text-white">
      <div class="container my-5"></div>
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://www.facebook.com/" role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>

            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://www.instagram.com/" role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://ie.linkedin.com/" role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>
      
            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://github.com/PatrykBal/ucd_pa_python_proj" role="button"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2024 Jake Robinson. All Rights Reserved.
        </div>
        <!-- Copyright -->
    </div>    
  </footer>
        


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<script src="/static/js/script.js"></script>

</body>
</html>

templates/blog.html
{% extends 'base.html' %}

{% block title %} Blog {% endblock %}


{% block body %}

<!-- Blog Section 1 -->
<div class="blog-section-container container">
    <p style="color: rgb(253, 211, 41);">BLOG</p>
    <h1 class= "blog-sec1-text"> Here I try to combine all things surfing and tech.</h1>
        <p class="blog-sec1-text2">The things I have writen that were interesting at some point.</p>
        <a href="{{ url_for('login_page') }}">Login</a>
  
</div>

<ul>
    {% for post in posts %}
    <li>
        <a href="{{ url_for('blog.post', post_id=post['id']) }}">{{ post['title'] }}</a>
    </li>
    {% endfor %}
</ul>



{% endblock %}

templates/create.html
{% extends 'base.html' %}

{% block title %} Create New Blog {% endblock %}


{% block body %}

<body>
    <div class="create-container">
        <h1>Create a New Blog Post</h1>
        <form method="POST" action="{{ url_for('blog.create') }}">
            <div class="textbox-container">
                <div>
                    <label for="title">Title:</label>
                    <input type="text" id="title" name="title" required>
                </div>
                <div>
                    <label for="content">Content:</label>
                    <textarea id="content" name="content" required></textarea>
                </div>
                <div>
                    <label for="author">Author:</label>
                    <input type="text" id="author" name="author" required>
                </div>
                <button type="submit">Create Post</button>
            </div>
        </form>
        <a href="{{ url_for('index') }}">Back to Home</a>
    </div>    
</body>


{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<!-- Hero Section -->
<div class="hero-section-container container">
    <p style="color: rgba(255, 255, 255, 0.3)">Hi, I'm Jake Robinson.</p>
    <h1 class= "hero-main-text" ><span style="color: rgb(255, 255, 2);">Champion Surfer </span> turned 
        <span style="color: rgb(253, 211, 41);">Design Innovator.</span></h1>
        <p class="text">Let me bring that same passion and precision to your next project.</p>
  
</div>

<!-- SECTION 1 -->
<div class="section1-container">
    <div class="owl-carousel owl-theme">
        <div class="item-video" data-merg="1">
            <a class="owl-video" autoplay muted loop href="https://www.youtube.com/watch?v=2Hz-HorXSFA"></a>
        </div>
        <div class="item-video" data-merg="1">
            <a class="owl-video" autoplay muted loop href="https://www.youtube.com/watch?v=1-DHMmrHmb0"></a>
        </div>
        <div class="item-video" data-merg="1">
            <a class="owl-video" autoplay muted loop href="https://www.youtube.com/watch?v=7BOhDaJH0m4"></a>
        </div>
    </div>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}


{% block body %}

<div class=" login-container">
    <h3 class="info" >{{info}} </h3>
    <form  action="/form_login" method="post">
        <h1 class="form-title">Login</h1>
        <div class="form-message form-message-error"></div>
        <div class="form-input-group">
            <input type="text" name='username' class="form-input" autofocus placeholder="Username or email">
        <div class="form-input-error-message"></div>
        </div>
        <div class="form-input-group">
            <input type="password" name='password' class="form-input" autofocus placeholder="Password">
            <div class="form-input-error-message"></div>
        </div>
        <button class="form-button" type="submit" value='Login'> Continue</button>
        <p class="form-text">
            <a href="#" class="form-link">Forgot your password?</a>
        </p>
        <p class="form-text">
            <a class="form-link" href="./" id="linkCreateAccount">Don't have account? Create account</a>
        </p>
    </form>
    

    <form class="form form-hidden" id="createAccount">
        <h1 class="form-title">Create Account</h1>
        <div class="form-message form-message-error"></div>
        <div class="form-input-group">
            <input type="text" id="signupUsername" class="form-input" autofocus placeholder="Username">
            <div class="form-input-error-message"></div>
        </div>
        <div class="form-input-group">
            <input type="text" class="form-input" autofocus placeholder="Email Address">
            <div class="form-input-error-message"></div>
        </div>
        <div class="form-input-group">
            <input type="password" class="form-input" autofocus placeholder="Password">
            <div class="form-input-error-message"></div>
        </div>
        <div class="form-input-group">
            <input type="password" class="form-input" autofocus placeholder=" Confirm Password">
            <div class="form-input-error-message"></div>
        </div>
        <button class="form-button" type="submit"> Continue</button>
        <p class="form-text">
            <a class="form-link" href="./" id="linkLogin">Already have an account ? Sign in</a>
        </p>
    </form>
</div>    

{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}


{% block body %}

body >
<br>
<br>
<h1 class="logout-h1">Welcome  <strong class="str" >{{name}}!</strong></h1>
<a href="{{ url_for('create') }}">Create Post</a>
<a  class="btn-logout" href="{{url_for('index')}}">Logout</a>
 

{% endblock %}

templates/posts.html
{% extends 'base.html' %}

{% block title %} Posts {% endblock %}


{% block body %}

<h1>{{ post['title'] }}</h1>
    <p>By {{ post['author'] }}</p>
    <p>{{ post['content'] }}</p>
    <a href="{{ url_for('index') }}">Back to Home</a>


{% endblock %}